### ISSUE TITLE
Gun able to shoot through walls v1.1

### ISSUE THREAD

**Issue by Destiri** [M1TTH/BountyHunter_GAME#5]
Alpha version 1.1

to reproduce: When pressed up against a thin wall or door, if the gun clips through it, it is able to shoot through it damaging enemies in the next room, "cheesing" the game

how it should work: the gun's bullets and the gun itself shouldn't be able to clip through the wall, should be collided with the wall.

**Comment by M1TTH** [comment]
Changed it so the guns can no longer stick through the walls and shoot enemies
