### ISSUE TITLE
Shield health v1.1

### ISSUE THREAD

**Issue by Destiri** [M1TTH/BountyHunter_GAME#7]
Alpha version 1.1

Unable to know when the shield is about to break or if it's losing durability. 

change the colour of the shiled depending on it's health like a Jackal from halo, or add some sort of cracks to the shield to indicate that it's about to disappear.

**Comment by M1TTH** [comment]
The color of the shield now changed depending on the health from 
Blue(100%) 
Yellow(75%) 
Orange(50%) 
Red (25%)
