### ISSUE TITLE
Health bars to enemies v1.1

### ISSUE THREAD

**Issue by Destiri** [M1TTH/BountyHunter_GAME#8]
Alpha version 1.1

People have been suggesting adding a health bar to enemies to let them know that they have been damaging them or how much health left is required for them to die.

I suggest adding a health bar below the enemies once they have been attacked to prevent clutter on the screen and disappear once the attacking has stopped.

**Comment by M1TTH** [comment]
Added enemy health bars and made it so they only show if you hit the enemy
