### ISSUE TITLE
Green enemy in wave room v1.1

### ISSUE THREAD

**Issue by Destiri** [M1TTH/BountyHunter_GAME#9]
Alpha version 1.1

The little minions that spawn are too overpowered if you get overwhelmed, also if attacked with the overpowered railgun, they multiply.

To prevent the overpowered feature, make the small minions unable to shoot, make them deal contact damage or make them explode themselves, give the player a reason to target them over the shielded target which is spawning them.
Fix the bug which is causing the duplication feature when you shoot them with the railgun.

**Comment by M1TTH** [comment]
Grene Minions have been changed to run at the player and explode instead of shooting 

Still working on the bug which is causing duplication with the railgun

**Comment by M1TTH** [comment]
Fixed the duplication bug when you shoot the minion with the railgun
